### PR TITLE
Update versions

### PR DESCRIPTION
**Pull request by lahirusamith**

### CODE REVIEW

**Review by daneshk — APPROVED** [review]

**Comment by anupama-pathirage** [comment]
@lahirusamith The commit messages and PR heading is not according to the best practices. Please correct them.

A properly formed Git commit subject line should always be able to complete the following sentence:

If applied, this commit will your subject line here

Refer [1] for more details.

[1] https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md#submit-your-contribution

**Comment by daneshk** [comment]
> @lahirusamith The commit messages and PR heading is not according to the best practices. Please correct them.
> 
> A properly formed Git commit subject line should always be able to complete the following sentence:
> 
> If applied, this commit will your subject line here
> 
> Refer [1] for more details.
> 
> [1] https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md#submit-your-contribution

Thanks, @anupama-pathirage for pointing this. @lahirusamith can you correct the commit message

**Comment by lahirusamith** [comment]
> @lahirusamith The commit messages and PR heading is not according to the best practices. Please correct them.
> 
> A properly formed Git commit subject line should always be able to complete the following sentence:
> 
> If applied, this commit will **_your subject line here_**
> 
> Refer [1] for more details.
> 
> [1] https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md#submit-your-contribution

Sorry ! my bad. I will correct it

**Comment by lahirusamith** [comment]
@anupama-pathirage Please check and verify the requested changes.

**Pull request merged**
